### ISSUE TITLE
Error during parsing of test_cgal_rc

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#10]
I have a file `/home/lrineau/.config/CGAL/test_cgal_rc` that contains:
```
--user member1
--passwd cg4any1
--tester lrineau
--tester-address Laurent.Rineau@geometryfactory.com
```
If I add the following line to it:
```
--tester-name "Laurent Rineau"
```
then the script display its usage and says:
```
test_cgal.py: error: unrecognized arguments: Rineau"
```
In my opinion, it does not like either the spaces in the option. The quote is not taken into account.

If I use the following line without quotes:
```
--tester-name Laurent Rineau
```
it displays almost the same:
```
test_cgal.py: error: unrecognized arguments: Rineau
```

In do not see how I can fill an option with a value that contains a space. What does the default parser [ArgumentParser.convert_arg_line_to_args](https://docs.python.org/dev/library/argparse.html#argparse.ArgumentParser.convert_arg_line_to_args)?

**Comment by bo0ts** [comment]
I just checked this case against the default argparse. It allows the space to be escaped with `\` and the argument to be surrounded with quotes.

It seems that the `convert_arg_line_to_args` override from the link you suggested to implement the advanced argument file parsing seems to be broken. I will investigate further on Wednesday.

**Comment by bo0ts** [comment]
I also think trying to fix this is moot. I just tried to run `./test_cgal --tester "Name With Spaces"` and the collect script failed during creation of the tar file.
