### ISSUE TITLE
Install eigen master on `Ubuntu-GCC_master_cpp20-Release`

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#108]
@maxGimeno Can you please modify this Dockerfile so that Eigen master version is used?

https://github.com/CGAL/cgal-testsuite-dockerfiles/blob/65a3d7188a009b05b5bdbdc3c73170785b448c51/Ubuntu-GCC_master_cpp20-Release/Dockerfile#L1-L14

**Comment by maxGimeno** [comment]
Done in #109
