### ISSUE TITLE
Use scripts to factorize the installation of deps between different Dockerfile

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#16]
Instead of copy-pasting a long list of `yum install ...` in all CentOS/Fedora containers, the RUN command could use a script to do the same job. That script could have the logic to detect x86_64/i686, and adapt the yum/dnf command line. That would help the factorization of Dockerfiles.

And same for Ubuntu/Debian, and the various ArchLinux Dockerfiles we may have.

Eventually we could even contribute those scripts to CGAL in a `contrib/` sub-directory (or `auxliary/`?).

**Comment by bo0ts** [comment]
IMO that would only centralize the dependency mess in a single file. Currently every special case is handled in the specific Dockerfile it needs handling.

For x86_64/i686 the differences are largely in the auxiliary packages needed to build things and this is also different between Debian/Fedora again, so there is not much use in centralizing this.

**Comment by lrineau** [comment]
All right.
