### ISSUE TITLE
Testsuite for our containers

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#17]
I think there should be a minimalist testsuite for the built containers.

It could be as simple as:
```
docker run --rm $image ls /usr/include/QGLViewer/qglviewer.h \
                          /usr/include/GL/glew.h \
                          /usr/include/eigen3/Eigen/Eigen
```
or similar...

**Comment by bo0ts** [comment]
5dea411 added a script that uses cmake to test a container. Future work would be to extend that script to version information etc.
