### ISSUE TITLE
Add `Qt5Help`

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#21]
One of the CGAL demos requires `Qt5Help`. See [the line `Periodic_3_triangulation_3_Demo` of the test results of CGAL-4.-Ic-81][1].

[1]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-81.shtml#Periodic_3_triangulation_3_Demo

**Comment by lrineau** [comment]
I have seen that 2c5f0aa and 2f1b823 should fix the issue.

But, on `debian-stable` and `debian-testing`, the test `test_container.py` reports:
```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5Help/Qt5HelpConfig.cmake:27 (message):
  The imported target "Qt5::Help" references the file

     "/usr/lib/x86_64-linux-gnu/qt5/bin/qcollectiongenerator"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/x86_64-linux-gnu/cmake/Qt5Help/Qt5HelpConfigExtras.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Qt5Help/Qt5HelpConfigExtras.cmake:6 (_qt5_Help_check_file_exists)
  /usr/lib/x86_64-linux-gnu/cmake/Qt5Help/Qt5HelpConfig.cmake:158 (include)
  CMakeLists.txt:30 (find_package)
```

**Comment by lrineau** [comment]
[It seems to be in the package `qttools5-dev-tools`](https://packages.debian.org/experimental/amd64/qttools5-dev-tools/filelist).

**Comment by bo0ts** [comment]
Debian package name is outright ridiculous.

**Comment by lrineau** [comment]
That's right! The packaging is strange, because there should be a dep. 

-------- Message d'origine --------
De : Philipp Moeller <notifications@github.com> 
Date : 2015/07/13  19:21  (GMT+01:00) 
À : CGAL/cgal-testsuite-dockerfiles <cgal-testsuite-dockerfiles@noreply.github.com> 
Cc : Laurent Rineau <laurent.rineau@cgal.org> 
Objet : Re: [cgal-testsuite-dockerfiles] Add `Qt5Help` (#21) 

Debian package name is outright ridiculous.
