### ISSUE TITLE
CentOS 6 needs libQGLViewer-qt5

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#22]
Our CentOS 6 images needs a version of libQGLViewer compiled with qt5.

**Comment by bo0ts** [comment]
Currently the CentOS 6 build of https://copr.fedoraproject.org/coprs/rineau/libQGLViewer-qt5/ is failing and installing libQGLViewer for Qt5 the normal way conflicts with libQGLViewer for Qt4. I would prefer installing it via the copr repository instead of having to hack on the build locally.

**Comment by lrineau** [comment]
CentOS-6 now has a Copr build.

https://copr.fedoraproject.org/coprs/rineau/libQGLViewer-qt5/monitor/

**Comment by bo0ts** [comment]
On yum the copr build has file conflicts with the `libQGLViewer-devel` package.

> Transaction Check Error:
>   file /usr/include/QGLViewer/camera.h from install of libQGLViewer-qt5-devel-2.5.1-8.el6.x86_64 conflicts with file from package libQGLViewer-devel-2.3.6-1.el6.x86_64
>   file /usr/include/QGLViewer/config.h from install of libQGLViewer-qt5-devel-2.5.1-8.el6.x86_64 conflicts with file from package libQGLViewer-devel-2.3.6-1.el6.x86_64
>   file /usr/include/QGLViewer/constraint.h from install of libQGLViewer-qt5-devel-2.5.1-8.el6.x86_64 conflicts with file from package libQGLViewer-devel-2.3.6-1.el6.x86_64
>   file /usr/include/QGLViewer/domUtils.h from install of libQGLViewer-qt5-devel-2.5.1-8.el6.x86_64 conflicts with file from package libQGLViewer-devel-2.3.6-1.el6.x86_64
>   file /usr/include/QGLViewer/frame.h from install of libQGLViewer-qt5-devel-2.5.1-8.el6.x86_64 conflicts with file from package libQGLViewer-devel-2.3.6-1.el6.x86_64
>   file /usr/include/QGLViewer/keyFrameInterpolator.h from install of libQGLViewer-qt5-devel-2.5.1-8.el6.x86_64 conflicts with file from package libQGLViewer-devel-2.3.6-1.el6.x86_64
>   file /usr/include/QGLViewer/manipulatedCameraFrame.h from install of libQGLViewer-qt5-devel-2.5.1-8.el6.x86_64 conflicts with file from package libQGLViewer-devel-2.3.6-1.el6.x86_64
>   file /usr/include/QGLViewer/manipulatedFrame.h from install of libQGLViewer-qt5-devel-2.5.1-8.el6.x86_64 conflicts with file from package libQGLViewer-devel-2.3.6-1.el6.x86_64
>   file /usr/include/QGLViewer/mouseGrabber.h from install of libQGLViewer-qt5-devel-2.5.1-8.el6.x86_64 conflicts with file from package libQGLViewer-devel-2.3.6-1.el6.x86_64
>   file /usr/include/QGLViewer/qglviewer.h from install of libQGLViewer-qt5-devel-2.5.1-8.el6.x86_64 conflicts with file from package libQGLViewer-devel-2.3.6-1.el6.x86_64
>   file /usr/include/QGLViewer/qglviewer_fr.qm from install of libQGLViewer-qt5-devel-2.5.1-8.el6.x86_64 conflicts with file from package libQGLViewer-devel-2.3.6-1.el6.x86_64
>   file /usr/include/QGLViewer/quaternion.h from install of libQGLViewer-qt5-devel-2.5.1-8.el6.x86_64 conflicts with file from package libQGLViewer-devel-2.3.6-1.el6.x86_64
>   file /usr/include/QGLViewer/vec.h from install of libQGLViewer-qt5-devel-2.5.1-8.el6.x86_64 conflicts with file from package libQGLViewer-devel-2.3.6-1.el6.x86_64

An easy solution would be to drop the old `libqglviewer` from the distro but that would break the requirement for running old testsuites.

**Comment by lrineau** [comment]
You should update `libQGLViewer-devel` to the version that is in Copr.

**Comment by bo0ts** [comment]
c6905a7 adds it for CentOS-6. There is no build for i686 yet. Do you plan to add that repo? Otherwise I'll install it manually on CentOS-6-32.

**Comment by lrineau** [comment]
Copr repos are not multi-arch. You need to tweak the repo file and add the following lines:
```
[rineau-libQGLViewer-qt5-i386]
name=Copr repo for libQGLViewer-qt5 owned by rineau (i386)
baseurl=https://copr-be.cloud.fedoraproject.org/results/rineau/libQGLViewer-qt5/epel-6-i386/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/rineau/libQGLViewer-qt5/pubkey.gpg
enabled=1
enabled_metadata=1
```

**Comment by bo0ts** [comment]
CentOS-6 and CentOS-6-32 now both have libQGLViewer for Qt4 and Qt5.
