### ISSUE TITLE
docker.io/cgal/testsuite-docker:ubuntu has Qt5-5.2.1 and Qt-5.3 is required

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#23]
We require Qt-5.3 at least for [`AA_UseDesktopOpenGL`](http://doc.qt.io/qt-5/qt.html#ApplicationAttribute-enum), introduced in Qt-5.3.

**Comment by bo0ts** [comment]
My personal opinion is, that CGAL 4.7 should be compatible with the latest Ubuntu when it is released. The distribution is really common and we should strive to support it. 

How hard would it be to work around that?

**Comment by sloriot** [comment]
My 2 cents: Not a big issue, we're talking about 3D demos only.

**Comment by lrineau** [comment]
I agree. I searched for "5.3" in the documentation of Qt-5.5, and I found out all the new thing in Qt-5.3 (because the documentation of Qt always says "Introduced by Qt-5.3" or similar).

I think the only adaptation we need is that [`AA_UseDesktopOpenGL`](http://doc.qt.io/qt-5/qt.html#ApplicationAttribute-enum).

**Comment by sloriot** [comment]
@lrineau who do you agree with?

**Comment by lrineau** [comment]
I agree with Philipp, because the modification is small. If that was too much work, I would not.

**Comment by lrineau** [comment]
I have a patch under construction...

**Comment by lrineau** [comment]
Addressed by the pull-request CGAL/cgal#239.

I will close this issue only once we have verified that it works.

**Comment by lrineau** [comment]
I confirm that the pull-request 
https://github.com/CGAL/cgal/pull/239 did solve the issue: compare [AABB demo in CGAL-4.7-Ic-107](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.7-Ic-107/AABB_tree_Demo/TestReport_lrineau_Ubuntu-Latest.gz) (good result) with [AABB demo in CGAL-4.7-Ic-106](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.7-Ic-106/AABB_tree_Demo/TestReport_lrineau_Ubuntu-Latest.gz) (compilation error).

I close this issue.
