### ISSUE TITLE
cgal.geomtryfactory.com was overloaded

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#27]
I just ran:
```
sudo systemctl stop docker
```
on cgal.geometryfactory.com because the machine was overloaded (the load was 90, where there are only six processors with hyperthreading, thus 12 threads).

The problem seems to be that the Docker testsuite of one day did not finish in less than a day, and was superimposed with the testsuite of the next day. Once that happens, that is even worst for the following day.

I do not know exactly why that happened, but we cannot allow ourself to overload that machine. I suggest that once a testsuite is started, it kills *all* the testsuite containers that may remain. And there must be also something in the controlling Python script, that detects that a new testsuite has been launched, and prevent to launch new containers for the old testsuite.

Cc: @sloriot @bo0ts
 
Sébastien, restart Docker once you have figured out a way that it no longer happens.

**Comment by bo0ts** [comment]
Are you launching the testsuite with the `--force-rm` option? Currently the python script will not start a new container while an old one is still running. If `--force-rm` is specified, the old container will be killed and removed before a new one is launched. So I'm curious how that could have happened.

Do you have a list of all containers at the time you detected the overload?

**Comment by lrineau** [comment]
Yes, I use `--force-rm` (see [my crontab](https://github.com/CGAL/cgal/blob/master/Maintenance/infrastructure/cgal.geometryfactory.com/crontab)). But if the script is configured to use 5 processors, and does not finish because the launch of the next day... Let's say the day N the containers C8 and C9  have not finished. And the new instance of the script launches containers C1 and C2. Then your two sets of containers try to use 10 processors instead of 5... And the machine is down.

**Comment by lrineau** [comment]
When I detected the overload, the load was so heavy that I was lucky to be able to shut down Docker. 

Knowing which containers or which packages consume the CPU is an interesting question, but here the bug is that we need a way to control the load if a testsuite is launched while another one is not finished.

**Comment by bo0ts** [comment]
The commits 93ed9f7 and 6266913 add the ability to handle such situations. Only a single instance of test_cgal can run at  once. This is checked with a pidfile in `/tmp`. Signals are now handled and containers associated with a testsuite are killed along with the `test_cgal` script.
