### ISSUE TITLE
Allow to read options from a file

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#3]
To avoid passing user and password on the command line, I would like that the script can read default options from a config file. `argparse` can read from file.

http://tricksntweaks.blogspot.be/2013/05/advance-argument-parsing-in-python.html

I suggest that:
  - The script loads and parse a default config file. Its path would be discovered using XDG: something like `xdg.BaseDirectory.load_first_config("CGAL") + "/test_cgal_rc"` (or something more pythonic to join paths).
  - The script also allow to load config files using the `@` prefix.

**Comment by bo0ts** [comment]
9d094a4 implements this. Notice that, if a test_cgal_rc exists, it will always be used and arguments have to be explicitly overwritten. This makes it easy to always have password and username specified and change other options at the same time.
