### ISSUE TITLE
Cleanup of the testsuite/ and testresults/ directories

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#30]
With the current version of the script, the sizes of the directories `testsuite/` and `testresults/` are increasing each day, until the partition is full.

- `upload_results()` should remove the file, once it is uploaded.
- the destructor of `Release` should remove the file that was downloaded, as well as the untarred release directory.

**Comment by bo0ts** [comment]
c8f0e8d adds clean-up for `upload_results`

**Comment by bo0ts** [comment]
ea2e4a7 and 1c5d0e9 add clean-up for extracted releases and downloaded tars
