### ISSUE TITLE
Create a Docker image for ICC 2016

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#32]

**Comment by bo0ts** [comment]
9f292b2 adds a Docker image with ICC 2016. I currently cannot test it since I do not have a license, but the installation seems to work since it complains about precisely that fact.

Let's close this after we have used the image to submit a testsuite.

**Comment by lrineau** [comment]
Can you remind me what I should do so that the compiler can read its license?

https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-10/Partition_2_Examples/TestReport_lrineau_CentOS7-ICC-2016.gz

**Comment by bo0ts** [comment]
You have to specify the directory containing the Intel License Files with `--intel-license` option of `test_cgal.py`.

**Comment by lrineau** [comment]
It seems that newest version of the Intel Compiler check the MAC address of the machine, and the license is attached to one MAC address.

I have seen the option `--mac-address` of `docker-run`. I think we will have to use it.

**Comment by lrineau** [comment]
https://software.intel.com/en-us/articles/how-to-find-the-host-id-for-the-named-user-license

**Comment by bo0ts** [comment]
35dc750 adds the ability to change the MAC address of the containers by specifying `--mac-address`. I tested running two testsuites with the same MAC concurrently and it worked. Let's check if this actually fixes the issue for the license.

**Comment by lrineau** [comment]
It is solved. See https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-19.shtml
