### ISSUE TITLE
Update CentOS7-ICC-2016 to ICC 2016 Update 1

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#34]

**Comment by bo0ts** [comment]
Is this fixed by f0f1c98 and the successive fixes?

**Comment by lrineau** [comment]
Not sure. I think there is a build issue with by patch. As the image is pretty big, I did not want to test the build locally. I am not sure that it eventually converged to a valid image definition.

**Comment by bo0ts** [comment]
https://hub.docker.com/r/cgal/testsuite-docker/builds/bu4l6yecfjzcepm3o4iv4n7/

There is still a syntax error in the curl command.
