### ISSUE TITLE
Add CentOS7-ICC-2016-Release

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#35]
Add a Release version of CentOS7-ICC-2016.

**Comment by sloriot** [comment]
Closed? The testsuite column is fully red...

**Comment by bo0ts** [comment]
@sloriot The red testsuite was related to centos7-icc-2016 image, this is about the centos7-icc-2016-release image. The other issue has been fixed in commit bcf4252
