### ISSUE TITLE
Test -std=c++1y before CGAL-4.8 is released

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#37]

**Comment by bo0ts** [comment]
I'm not sure this is a good idea. The name `c++1y` is deprecated in gcc (https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html) and clang (after 3.4 http://clang.llvm.org/cxx_status.html#cxx14). I'm already adding a clang testsuite with C++14.

Do you want a gcc testsuite with c++14 as well?

**Comment by lrineau** [comment]
Right, C++14. The test of gcc-6.0 with C++1z is another issue.
