### ISSUE TITLE
Kill all containers before starting

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#4]
The test suite process should have an option to kill all existing containers that it has launched. That will be used to ensure that the testsuite of the previous release (of the day before) no longer runs.

The details are to be discussed.

**Comment by bo0ts** [comment]
I just added the naming feature and this already takes care of one half of the problem: before creating a container, it checks if a container with that name already exists. If the container exists, but is exited, it will remove the container. If the container exists, but is still running, it will not create a new container.

The flag you want could just change the behavior from skipping creation of a new container to force killing it. This has several problems: you lose the logs of a still running testsuite. We could implement saving the logs to some place, but would need to work out the details of that.

**Comment by lrineau** [comment]
With our current testsuite process, I sometimes force-kill and remove some platforms. Anyway, most testsuite that are late are swapping, and test results from those tests are cluttered with timeout errors. Killing them without having any results is an acceptable option. Another option would be to stop them and rename then, for a post-mortem autopsy.
