### ISSUE TITLE
test_cgal starts all containers at once

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#6]
I have tried `test_cgal` without arguments (`--user` and `--passwd` were in the rc file). The script launched five containers, and they are all running at the same time. Hopefully, they compile without the `-j` option.

**Comment by bo0ts** [comment]
See #7 gives an overview over the added capabilities to respect and set maximum cpus. I still need to inspect the behavior of the collect script to see how it determines how many jobs to use.

**Comment by lrineau** [comment]
This bug has been solved with the implementation of last Monday:
https://github.com/CGAL/cgal-testsuite-dockerfiles/tree/c2954faa2aaf9eb5844db0ea2ad3ee2546547179
