### ISSUE TITLE
How to control how many jobs are used, in a container?

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#7]
In the current CGAL testsuite, one can launch a testsuite with parallel testing, using a `-j<N>` option to GNU make. It should be possible with the containers.

**Comment by bo0ts** [comment]
The commits c2954fa 9246db9 11468f1 1cb3d11 implement the ability to specify a maximum number of CPUs to use and the amount of CPUs a single container should be allocated, the ability to launch as many as possible containers, and the queuing of not yet launched containers.

**Comment by lrineau** [comment]
The following seems to document several ways to handle the resources used by containers:
https://goldmann.pl/blog/2014/09/11/resource-management-in-docker/#_example_managing_the_cpu_shares_of_a_container

**Comment by bo0ts** [comment]
Yes, there are two ways. I use cpusets, because cpu shares don't meet our requirement of preventing a container of consuming all available resources of a machine.

**Comment by lrineau** [comment]
I think the non-container services also have shares. Anyway, the Linux kernel handles pretty well the CPU resources, with its scheduler. I am more concerned about the memory and I/O (if anything starts swapping).

**Comment by lrineau** [comment]
Anyway, this bug report is about controlling which parameter `-j<N>` is passed to `make -k -fmakefile2`, within a given container. As far as I can see for the moment, whatever `--container-cpus` is passed to `test_cgal.py`, then the testsuite will use only one job.
