### ISSUE TITLE
Missing dependencies versions, in test results

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#8]
In a result text file like `results_lrineau_x86-64_Linux-Fedora19_g++-4.8_m32.txt`, generated by `autotest_cgal`, there are lines starting with `-- USING`. For example:
```
CGAL_VERSION 4.7-Ic-9
TESTER lrineau
TESTER_NAME renoir (GF)
TESTER_ADDRESS Laurent.Rineau__cgal_testsuite@normalesup.org
CGAL_TEST_PLATFORM x86-64_Linux-Fedora19_g++-4.8_m32
General installation log file: ../../installation.log
Host-specific installation log file: ../installation.log
-- USING CMake version: 2.8.12
-- USING GCC_VERSION = '4.8.3 20140911 (Red Hat 4.8.3-7)'
-- USING CXXFLAGS = '-m32 -frounding-math -Wall -O3'
-- USING LDFLAGS = ' '
-- USING GMP_VERSION = '5.1.2'
-- USING MPFR_VERSION = '3.1.2'
-- USING BOOST_VERSION = '1.54.0'
-- USING QT_VERSION = '3.3.8b'
-- USING OPENGL_VERSION = '2.1'
-- USING QT4_VERSION = '4.8.6'
-- USING ZLIB_VERSION = '1.2.8'
```

If I remember well, those lines are just a result of `grep USING` over the CMake log. These lines are important, because they are used to fill the first table in the test results.

See https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-24.shtml

**Comment by lrineau** [comment]
That will probably be just one line to add in the entrypoint script.

**Comment by bo0ts** [comment]
3fdfcc0 should address this as well. The USING entries were omitted since installation.log could not be found.
