### ISSUE TITLE
CentOS 6: install VTK-6.x, LASlib, TBB, and OpenCV

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#80]
Our CentOS 6 will become the base image for the automatic creation of Linux AppImage. We need to have all dependencies:

1. OpenCV: easy, it is packaged.
2. VTK-6.x: to build from sources.
3. LASlib: to build from sources, like for the other platforms.
4. TBB: install the prebuilt binaries (use the recipe of https://github.com/lrineau/bundle-CGAL-3D-demo/blob/13329028261dc316d6b87d7e4b733645a2b0aa07/Dockerfile#L25).

**Comment by maxGimeno** [comment]
LASlib requieres c++11, which we do not want in this image. 
We should close this issue and put the bundle image in the testsuite instead.

**Comment by lrineau** [comment]
The 3D demo also requires C++11. I do not see the problem. Anyway, we use the Redhat Developer Toolset to get a modern compiler.

**Comment by lrineau** [comment]
OK, now I see the problem: our current configuration of the CentOS 6 platform uses g++ 4.4, that cannot use C++11.

**Comment by maxGimeno** [comment]
So what should we do ? test g++ 4.4 on another platform ? use another platform for the AppImage ? ignore LASLib ?

**Comment by lrineau** [comment]
Maybe our CentOS 6 image could use a more recent toolset.

**Comment by maxGimeno** [comment]
Do we still want CentOS6 as base image ? The image is not even tested anymore.

**Comment by lrineau** [comment]
You are right: now it should be an image based on CentOS 7.

**Comment by lrineau** [comment]
CentOS-6 is EOL: https://wiki.centos.org/About/Product
