### ISSUE TITLE
Missing information, in the results of `Installation`

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#9]
See the beginning of https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.7-Ic-24/Installation/TestReport_lrineau_Debian-Testing.gz

**Comment by lrineau** [comment]
That will probably be a few lines to add in the entrypoint: before the "collect results" script is launched, `test/Installation/error.txt` must be modified if I remember well.

**Comment by bo0ts** [comment]
This was caused since the collect scripts uses relative paths for everything. I moved the build directory to the right place before launching the script and this should fix this.

**Comment by bo0ts** [comment]
IMO this has been fixed in the referenced commit 3fdfcc0e521abd66e9ff704208a8158561248059, broken somewhere in between and then fixed again in 557051a and is now stable.
